input.onButtonPressed(Button.A, function () {
    basic.showNumber(1)
})
input.onGesture(Gesture.Shake, function () {
    basic.showNumber(1)
    basic.pause(25)
    basic.showNumber(2)
    basic.pause(25)
    basic.showNumber(3)
    basic.pause(25)
    basic.showNumber(4)
    basic.pause(25)
    basic.showNumber(5)
    basic.pause(25)
    basic.showNumber(6)
    basic.clearScreen()
    basic.pause(800)
    basic.showNumber(randint(1, 6))
})
input.onButtonPressed(Button.AB, function () {
    basic.showNumber(1)
    basic.pause(25)
    basic.showNumber(2)
    basic.pause(25)
    basic.showNumber(3)
    basic.pause(25)
    basic.showNumber(4)
    basic.pause(25)
    basic.showNumber(5)
    basic.pause(25)
    basic.showNumber(6)
    basic.clearScreen()
    basic.pause(800)
    basic.showNumber(randint(1, 6))
})
input.onButtonPressed(Button.B, function () {
    basic.showNumber(6)
})
